import { MigrationInterface, QueryRunner } from 'typeorm';

export class RenameMigrationsPrimaryKey20260805000100 implements MigrationInterface {
  name = 'RenameMigrationsPrimaryKey20260805000100';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
DO $$
DECLARE
  old_constraint_name text;
BEGIN
  SELECT constraint_record.conname
  INTO old_constraint_name
  FROM pg_constraint AS constraint_record
  WHERE constraint_record.conrelid = to_regclass('public.migrations')
    AND constraint_record.contype = 'p'
    AND constraint_record.conname <> 'pk_migrations'
    AND NOT EXISTS (
      SELECT 1
      FROM pg_constraint AS expected_constraint
      WHERE expected_constraint.conrelid = constraint_record.conrelid
        AND expected_constraint.conname = 'pk_migrations'
    );

  IF old_constraint_name IS NOT NULL THEN
    EXECUTE format(
      'ALTER TABLE public.migrations RENAME CONSTRAINT %I TO %I',
      old_constraint_name,
      'pk_migrations'
    );
  END IF;
END $$;
`);
  }

  async down(): Promise<void> {
    // The previous name is generated by TypeORM and is not stable across DBs.
  }
}
