import { MigrationInterface, QueryRunner } from 'typeorm';

const uniqueConstraints = [
  { tableName: 'patients', columnName: 'hn', constraintName: 'uq_patients_hn' },
  {
    tableName: 'patients',
    columnName: 'id_card',
    constraintName: 'uq_patients_id_card',
  },
  {
    tableName: 'processed_events',
    columnName: 'event_id',
    constraintName: 'uq_processed_events_event_id',
  },
  {
    tableName: 'medical_records',
    columnName: 'visit_id',
    constraintName: 'uq_medical_records_visit_id',
  },
  {
    tableName: 'invoices',
    columnName: 'visit_id',
    constraintName: 'uq_invoices_visit_id',
  },
] as const;

/**
 * TypeORM synchronize keeps an existing unique constraint when only its name
 * changes. Rename those constraints in place so existing service databases
 * match the explicit names declared by their entities.
 */
export class RenameUniqueConstraints20260805000000 implements MigrationInterface {
  name = 'RenameUniqueConstraints20260805000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    for (const constraint of uniqueConstraints) {
      await queryRunner.query(renameConstraintSql(constraint));
    }
  }

  async down(): Promise<void> {
    // Previous names were generated by PostgreSQL/TypeORM and differ between
    // databases, so there is no stable name to restore during a rollback.
  }
}

function renameConstraintSql({
  tableName,
  columnName,
  constraintName,
}: (typeof uniqueConstraints)[number]): string {
  return `
DO $$
DECLARE
  old_constraint_name text;
BEGIN
  SELECT constraint_record.conname
  INTO old_constraint_name
  FROM pg_constraint AS constraint_record
  WHERE constraint_record.conrelid = to_regclass('public.${tableName}')
    AND constraint_record.contype = 'u'
    AND pg_get_constraintdef(constraint_record.oid) = 'UNIQUE (${columnName})'
    AND constraint_record.conname <> '${constraintName}'
    AND NOT EXISTS (
      SELECT 1
      FROM pg_constraint AS expected_constraint
      WHERE expected_constraint.conrelid = constraint_record.conrelid
        AND expected_constraint.conname = '${constraintName}'
    );

  IF old_constraint_name IS NOT NULL THEN
    EXECUTE format(
      'ALTER TABLE public.${tableName} RENAME CONSTRAINT %I TO %I',
      old_constraint_name,
      '${constraintName}'
    );
  END IF;
END $$;
`;
}
